##############################################################################
# Identifier map. Used to lookup valid identifier names.

identifier_map = {
    'cards' : ['cards'],
    'emax' : ['emax'],
    'enode' : ['enode'],
    'err' : ['err'],
    'errint' : ['errint'],
    'errmax' : ['errmax'],
    'hk' : ['hk'],
    'ielas' : ['ielas'],
    'iopt' : ['iopt'],
    'iopp' : ['iopp'],
    'iprint' : ['iprint'],
    'iwt' : ['iwt'],
    'iz_aw' : ['iz_aw'],
    'iza01' : ['iza01'],
    'iza02' : ['iza02'],
    'iza03' : ['iza03'],
    # XXX: Use one identifier for material?
    'mat' : ['mat', 'matd'],
    'matd' : ['matd', 'mat', 'material'],
    'mte' : ['mte'],
    'mti' : ['mti'],
    'nace' : ['nace'],
    'nbint' : ['nbint'],
    'ncards' : ['ncards'],
    'nendf' : ['nendf', 'endf_input_tape'],
    'newfor' : ['newfor'],
    'ndir' : ['ndir'],
    'ngend' : ['ngend'],
    'ngrid' : ['ngrid'],
    'nmix' : ['nmix'],
    'ntype' : ['ntype'],
    'npend' : ['npend', 'pendf_input_tape'],
    'nxtra' : ['nxtra'],
    'suff' : ['suff'],
    'tempd' : ['tempd'],
    'tempr' : ['tempr'],
    'thin01' : ['thin01'],
    'thin02' : ['thin02'],
    'thin03' : ['thin03'],
    'tlabel' : ['tlabel'],
    'tname' : ['tname'],
}